// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

import { Seq } from '../../math/seq';
const fib = Seq.fibonacci;

export default function euler002() {
  let fibs = fib(100);
  for (let i = 100; fibs[fibs.length - 1] < 4000000; i += 20) {
    fibs = fibs(i);
  }
  return fibs
    .filter(x => x < 4000000)
    .reduce((prev, curr) => (curr % 2 === 0 ? prev + curr : prev), 0);
}
